// Generated by IcedCoffeeScript 108.0.9
(function() {
  var initDataTables;

  $(function() {
    console.log("aaa");
    return initDataTables();
  });

  initDataTables = function() {
    return $("#mata").DataTable();
  };

}).call(this);

//# sourceMappingURL=Search.js.map
