// Generated by IcedCoffeeScript 108.0.9
(function() {
  this.sendInsert = function() {
    var address, description, form, title;
    form = $("#creation");
    title = form.find(".title").text().trim();
    address = form.find(".address").text().trim();
    description = form.find(".description").text().trim();
    return $("<div></div>").addClass("just-inserted").css("display", "none").insertAfter("#submitted h2").load("" + window.location.href + "&Action=Insert&title=" + title + "&address=" + address + "&description=" + description + " #submitted article:first", function() {
      $(this).slideDown({
        complete: function() {
          return $(this).find("article").unwrap();
        }
      });
      prepareArticle($(this));
      return console.log("done inserting and loading!");
    });
  };

}).call(this);

//# sourceMappingURL=AddLink.js.map
