// Generated by IcedCoffeeScript 108.0.9
(function() {
  var addOption, deleteOption;

  this.submitSimilar = function() {
    var selected;
    selected = $("#new-similar select").val();
    return $.get("" + window.location.href + "&new-similar=" + selected, function(data) {
      var newSimilars;
      newSimilars = $(data).find("#submitted-similars").children();
      $("#submitted-similars").replaceWith(newSimilars);
      deleteOption(selected);
      return console.log("done submitting similar");
    });
  };

  deleteOption = function(address) {
    var elem;
    elem = $("#similars option:contains('" + address + "')");
    return elem.remove();
  };

  this.deleteSimilar = function() {
    var address, elem, target;
    target = $(event.currentTarget);
    address = target.siblings(".address").text();
    elem = target.parent(".similar-link");
    return $.get("" + window.location.href + "&del-similar=" + address, function() {
      elem.slideUp("fast");
      addOption(address);
      return console.log("done deleting similar");
    });
  };

  addOption = function(address) {
    var list;
    list = $("#similars select");
    return list.append("<option>" + address + "</option>");
  };

}).call(this);

//# sourceMappingURL=AddSimilar.js.map
