// Generated by IcedCoffeeScript 108.0.9
(function() {
  var convertDate, convertDates, prepareArticle, rememberInitialValue;

  $(function() {
    var article, _i, _len, _ref;
    _ref = $("#submitted article");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      article = _ref[_i];
      prepareArticle($(article));
    }
    return setInterval(convertDates, 59000);
  });

  prepareArticle = function(article) {
    var editable, _i, _len, _ref, _results;
    convertDate(article.find(".date.difference"));
    _ref = article.find("[contenteditable]");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      editable = _ref[_i];
      _results.push(rememberInitialValue($(editable)));
    }
    return _results;
  };

  convertDates = function() {
    var elem, _i, _len, _ref, _results;
    _ref = $(".date.difference");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      elem = _ref[_i];
      _results.push(convertDate($(elem)));
    }
    return _results;
  };

  convertDate = function($elem) {
    var date, distance;
    date = $elem.attr("abs-date");
    distance = moment(date, "DD-MMM-YY HH:mm:ss").fromNow();
    if (distance !== "Invalid date") {
      return $elem.text(distance);
    }
  };

  rememberInitialValue = function($elem) {
    var value;
    value = $elem.text().trim();
    $elem.data("original", value);
    return $elem.data("db-cache", value);
  };

  this.focused;

  this.registerFocus = function(id, type) {
    return this.focused = {
      id: id,
      type: type
    };
  };

  this.updateFocused = function() {
    var content, date, elem, f, field, formattedDate, id, indicator, lastContent, type;
    id = this.focused.id;
    type = this.focused.type;
    if (type !== "title" && type !== "address" && type !== "description") {
      console.error("Invalid focused type: " + type);
      return;
    }
    elem = $("[db-id='" + id + "']");
    field = elem.find("." + type);
    content = field.text().trim();
    indicator = elem.find('.working-indicator');
    lastContent = field.data("last-content");
    if (content === field.data("db-cache")) {
      if (!!field.data("update-timeout")) {
        clearTimeout(field.data("update-timeout"));
      }
      indicator.css("visibility", "hidden");
      return;
    }
    if ((lastContent != null) && lastContent === content) {
      return;
    }
    field.data("last-content", content);
    if (type === "address") {
      elem.find(".favicon").attr("src", "http://www.google.com/s2/favicons?domain_url=" + content);
      elem.find(".visit-link").attr("title", "Visit " + content).attr("href", "" + (prependHttp(content)));
    }
    indicator.css("visibility", "visible");
    date = elem.find(".date.difference");
    formattedDate = moment().format("DD-MMM-YY HH:mm:ss");
    date.attr("abs-date", formattedDate).attr("title", "Date updated: " + formattedDate);
    if (!!field.data("update-timeout")) {
      clearTimeout(field.data("update-timeout"));
    }
    f = function() {
      return updateDB(type, content, id, indicator, date, field);
    };
    return field.data("update-timeout", setTimeout(f, 2000));
  };

  this.prependHttp = function(link) {
    var start, toPrepend;
    toPrepend = "http://";
    start = link.slice(0, toPrepend.length);
    if (start !== toPrepend) {
      return toPrepend + link;
    }
    return link;
  };

  this.updateDB = function(type, value, id, indicator, date, field) {
    return $.ajax({
      url: "" + window.location.href + "&Action=Update&field=" + type + "&value=" + value + "&id=" + id
    }).done(function() {
      field.data("db-cache", value);
      indicator.css("visibility", "hidden");
      convertDate(date);
      return console.log("done updating!");
    });
  };

  this.sendInsert = function() {
    var address, description, form, title;
    form = $("#creation");
    title = form.find(".title").text().trim();
    address = form.find(".address").text().trim();
    description = form.find(".description").text().trim();
    console.log("url = " + window.location.href + "&Action=Insert&title=" + title + "&address=" + address + "&description=" + description);
    return $("<div></div>").addClass("just-inserted").css("display", "none").insertAfter("#submitted h2").load("" + window.location.href + "&Action=Insert&title=" + title + "&address=" + address + "&description=" + description + " #submitted article:first", function() {
      $(this).slideDown({
        complete: function() {
          return $(this).find("article").unwrap();
        }
      });
      prepareArticle($(this));
      return console.log("done inserting and loading!");
    });
  };

  this.sendDelete = function(id) {
    return $.ajax({
      url: "" + window.location.href + "&Action=Delete&id=" + id
    }).done(function() {
      $("[db-id='" + id + "']").slideUp();
      return console.log("done deleting!");
    });
  };

}).call(this);

//# sourceMappingURL=AddUpdateDeleteLink.js.map
