// Generated by IcedCoffeeScript 108.0.9
(function() {
  var convertDatesShort;

  $(function() {
    return convertDatesShort();
  });

  convertDatesShort = function() {
    var $elem, distance, elem, original, shortened, _i, _len, _ref;
    _ref = $(".date.short-diff");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      elem = _ref[_i];
      $elem = $(elem);
      original = $elem.text();
      distance = moment(original, "DD-MMM-YY HH:mm:ss").fromNow(true);
      if (distance === "Invalid Date") {
        return;
      }
      shortened = distance.replace(/\s*a few seconds\s*/i, "now").replace(/\s*seconds?\s*/i, "s").replace(/\s*minutes?\s*/i, "m").replace(/\s*hours?\s*/i, "h").replace(/\s*days?\s*/i, "d").replace(/\s*months?\s*/i, "mo").replace(/\s*years?\s*/i, "y").replace(/\s*a\s*/i, "1");
      $elem.text(shortened);
    }
  };

}).call(this);

//# sourceMappingURL=ConvertDatesShort.js.map
