// Generated by IcedCoffeeScript 108.0.9
(function() {
  var convertDateShort;

  $(function() {
    return convertDates();
  });

  this.convertDates = function() {
    var elem, _i, _j, _len, _len1, _ref, _ref1, _results;
    _ref = $(".date.difference");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      elem = _ref[_i];
      convertDate($(elem));
    }
    _ref1 = $(".date.short-diff");
    _results = [];
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      elem = _ref1[_j];
      _results.push(convertDateShort($(elem)));
    }
    return _results;
  };

  this.convertDate = function($elem) {
    var date, distance;
    date = $elem.attr("abs-date");
    distance = moment(date, "DD-MMM-YY HH:mm:ss").fromNow();
    if (distance !== "Invalid date") {
      return $elem.text(distance);
    }
  };

  convertDateShort = function($elem) {
    var distance, original, shortened;
    original = $elem.text();
    distance = moment(original, "DD-MMM-YY HH:mm:ss").fromNow(true);
    if (distance === "Invalid Date") {
      return;
    }
    shortened = distance.replace(/\s*a few seconds\s*/i, "now").replace(/\s*seconds?\s*/i, "s").replace(/\s*minutes?\s*/i, "m").replace(/\s*hours?\s*/i, "h").replace(/\s*days?\s*/i, "d").replace(/\s*months?\s*/i, "mo").replace(/\s*years?\s*/i, "y").replace(/\s*a\s*/i, "1");
    return $elem.text(shortened);
  };

}).call(this);

//# sourceMappingURL=ConvertDates.js.map
