// Generated by IcedCoffeeScript 108.0.9
(function() {
  var convertDate, convertDates, initDataTables;

  $(function() {
    console.log("aaa");
    return initDataTables();
  });

  initDataTables = function() {
    return convertDates();
  };

  convertDates = function() {
    var elem, _i, _len, _ref, _results;
    _ref = $(".date.difference");
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      elem = _ref[_i];
      _results.push(convertDate($(elem)));
    }
    return _results;
  };

  convertDate = function($elem) {
    var date, distance;
    date = $elem.attr("abs-date");
    distance = moment(date, "DD-MMM-YY HH:mm:ss").fromNow();
    console.log("" + date + " is " + distance);
    if (distance !== "Invalid date") {
      return $elem.text(distance);
    }
  };

}).call(this);

//# sourceMappingURL=Search.js.map
