// Generated by IcedCoffeeScript 108.0.9
(function() {
  var visuallyToggle;

  this.sendToggle = function(address) {
    var elem;
    elem = $(event.currentTarget);
    return $.ajax({
      url: "Link?addr=" + address + "&toggle-fav"
    }).done(function() {
      console.log("done toggling fav");
      return visuallyToggle(elem);
    });
  };

  visuallyToggle = function(elem) {
    var count, indicator, isFavorited;
    indicator = elem.find(".fav-indicator");
    count = elem.find(".fav-count");
    isFavorited = indicator.hasClass("star");
    console.log("is fav = " + isFavorited + ", count = " + (count.text()));
    if (isFavorited) {
      indicator.removeClass("star");
      indicator.addClass("no-star");
      return count.text(+count.text() - 1);
    } else {
      indicator.addClass("star");
      indicator.removeClass("no-star");
      return count.text(+count.text() + 1);
    }
  };

}).call(this);

//# sourceMappingURL=ToggleFavorites.js.map
