// Generated by IcedCoffeeScript 108.0.9
(function() {
  var toggleCategoryName, visuallyToggle;

  this.sendToggle = function(address) {
    var elem;
    elem = $(event.currentTarget);
    return $.ajax({
      url: "Link?addr=" + address + "&toggle-fav"
    }).done(function() {
      console.log("done toggling fav");
      return visuallyToggle(elem);
    });
  };

  visuallyToggle = function(elem) {
    var count, indicator, isFavorited;
    indicator = elem.find(".fav-indicator");
    count = elem.find(".fav-count");
    isFavorited = indicator.hasClass("star");
    if (isFavorited) {
      indicator.removeClass("star");
      indicator.addClass("no-star");
      count.text(+count.text() - 1);
    } else {
      indicator.addClass("star");
      indicator.removeClass("no-star");
      count.text(+count.text() + 1);
    }
    return toggleCategoryName(elem.siblings(".category"), isFavorited);
  };

  toggleCategoryName = function(name, isFavorited) {
    if (!isFavorited) {
      name.removeAttr("hidden");
      return name.text("uncategorized");
    } else {
      return name.attr("hidden", "");
    }
  };

}).call(this);

//# sourceMappingURL=ToggleFavorites.js.map
